SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET@OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS Quench DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE Quench ;

DROP TABLE IF EXISTS Quench.drink ;

CREATE TABLE IF NOT EXISTS Quench.drink (
drinkName varchar(25) NOT NULL,
cityName varchar(40) NOT NULL,
drinkPrice INT(5) NOT NULL,
)
ENGINE = InnoDB;